<div class="row">
	<div class="row">
		<span class="fa-stack">
			<span class="fa fa-user fa-stack-2x"></span>
			<span class="fa fa-cog fa-stack-1x" style="color: white; margin-left: 5px;margin-top: 7px "></span>
		</span>
		<span class="sectionhd h5">System Adminstrator</span>
	</div>
	<div class="col-lg-12">
		<section class=" col-xs-5  col-sm-3 col-md-2">
			<span>
				<a href="addauditee.php"><i class="fa fa-university fa-2x">	
					</i> <span>Auditees</span>
				</a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3 col-md-2">
			<span>
				<a href="addstaff.php"><span class="fa fa-user-plus fa-2x"></span> <span>Staff</span></a>
			</span>
			
		</section>
		<section class=" col-xs-5  col-sm-3 col-md-2">
			<span>
				<a href="addbranch.php"><span class="fa fa-suitcase  fa-2x"></span><span>Audit Branches / Units</span></a>
			</span>
		</section>
		<section class="col-xs-5  col-sm-3 col-md-2">
			<span>
				<a href="audits.php"><span class="fa fa-lightbulb-o fa-2x"></span><span>Audits</span></a>

			</span>
		</section>
		
	</div>
</div>