<div class="row">
	<div class="row">
		<span class="fa-stack">
			<span class="fa fa-user-circle fa-stack-2x"></span>
		</span>
		<span class="sectionhd h5">Branch Head</span>
	</div>
	<div class="col-lg-12">
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-wpforms fa-2x"></span> <span>Create Audit</span></a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-user fa-2x"></span> <span>Compose Team</span></a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-file-o  fa-2x"></span><span>Competency Matrix</span></a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-server fa-2x"></span> <span>Resourcess</span></a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-stack-exchange fa-2x"></span><span>All Audits</span></a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-users fa-2x"></span><span>My Staff</span></a>
			</span>
		</section>
		
	</div>
</div>