		<footer>
			<small>
				<div class="container">
					<p class="text-center">Ghana Audit Service <br> Audit Management Information System</p>
				</div>
			</small>
		</footer>
		<script src="js/jquery-3.2.1.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui/jquery-ui.min.js"></script>
		<script src="js/main.js"></script>
	</body>
</html>