<?php require "core/init.php" ?>
<!DOCTYPE html>
<html>
	<head>
		<title>Audit Management Information System</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width = device-width, initial-scale = 1">
		<link rel="shortcut icon" type="image/x-icon" href="images/amis.png" />
		<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="css/main.css">
	</head>
	<body>
		<!-- <header class="bgimage">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<p class="text-center">
						<span class="h1">Ghana Audit Service <br>
						<span class="h3">Audit Management Information System (AMIS)
						</p>
					</div>
				</div>
			</div>
		</header> -->



