	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<div class="navbar-header">
					<a href="/amis	" class="navbar-brand">
						<!-- <img src="images/amis.png"> -->
						GAS AMIS
					</a>
				</div>
				<li><a href="/amis"><span class="fa fa-tachometer fa-lg "></span>Dashbord</a></li>
				<li><a href="/amis"><span class="fa fa-wpforms fa-lg "></span>My Audit</a></li>
				<!--
				<li><a href="#"><span class="fa fa-wpforms fa-lg" ></span>Create Audit</a></li>
				<li><a href="#"><span class="fa fa-server  fa-lg " ></span>Resources</a></li> -->
				<li><a href="#"><span class="fa fa-paper-plane fa-lg " ></span>Messages</a></li>
			</ul>
		</div>
	</nav>
