
<div class="row">
	<div class="row">
		<span class="fa-stack">
			<span class="fa fa-user fa-stack-2x"></span>
		</span>
		<span class="sectionhd h5">Staff</span>
	</div>
	<div class="col-lg-12">
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-pencil-square-o fa-2x"></span> <span>Assigned Audits</span></a>
			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-database fa-2x"></span> <span>Working Papers</span></a>
			</span>
		</section>
	</div>
</div>