<div class="row">
	<div class="row">
		<span class="fa-stack">
			<span class="fa fa-user fa-stack-2x"></span>
			<span class="fa fa-info fa-stack-1x" style="color: white; margin-left: 0px;margin-top: 7px "></span>
		</span>
		<span class="sectionhd h5">Team Leader</span>
	</div>

	<div class="col-lg-12">
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-object-group fa-2x"></span> <span>Budget Working Paper</span></a>

			</span>
		</section>
		<section class=" col-xs-5  col-sm-3  col-md-2">
			<span>
				<a href=""><span class="fa fa-stack-overflow fa-2x"></span> <span>Reports</span></a>
			</span>
		</section>
	</div>
</div>

